### ISSUE TITLE
Jquery

### ISSUE THREAD

**Issue by mulhoon** [Normally/Fingerprints.js#1]
Awesome! But would be nice to not depend on jquery.

**Comment by timdiacon** [comment]
shut up

**Comment by timdiacon** [comment]
How often are you gonna make a prototype that doesn't use jQuery... but yeah I am planning on removing the dependency as was annoying me that it was there.

**Comment by mulhoon** [comment]
Ha. Nobody uses jquery anymore!

**Comment by mulhoon** [comment]
Jquery selection in one line...
https://gist.github.com/mulhoon/a9d554544fe6dd875f7682f147eb4e2d

**Comment by timdiacon** [comment]
Done mother sucker
